export const FORMULARIO_MALETA = 'FORMULARIO_MALETA';
export const OBTENER_MALETA = 'OBTENER_MALETA';
export const AGREGAR_MALETA = 'AGREGAR_MALETA';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const MALETA_ACTUAL = 'MALETA_ACTUAL';
export const ELIMINAR_MALETA = 'ELIMINAR_MALETA';
export const MALETA_ERROR = 'MALETA_ERROR';

export const MATERIAL_MALETA = 'MATERIAL_MALETA';
export const AGREGAR_MATERIAL = 'AGREGAR_MATERIAL';
export const VALIDAR_MATERIAL = 'VALIDAR_MATERIAL';
export const ELIMINAR_MATERIAL = 'ELIMINAR_MATERIAL';
export const MATERIAL_ACTUAL = 'MATERIAL_ACTUAL';
export const ACTUALIZAR_MATERIAL = 'ACTUALIZAR_MATERIAL';
export const LIMPIAR_MATERIAL = 'LIMPIAR_MATERIAL';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';
